server:
  port: ${port:8080}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.60:3306/my-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.1.60
    port: 6379
    database: 0
    password: 123456
  rabbitmq:
    host: 192.168.1.60
    port: 5672
    virtual-host: itzixi
    username: test
    password: test
